name: 'Terraform - Dev'

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: Select Terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches: 
    - dev
    paths:
    - dev/**
  pull_request:
    branches:
    - dev
    paths: 
    - dev/**

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    env:
      # AWS secrets
      TF_VAR_project: 'poc'
      TF_VAR_env: 'dev'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure GH_TOKEN is properly set

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './dev'
        tf_actions_comment: true

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.7
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './dev'
        tf_actions_comment: true
        args: '-var="github_token=${{ secrets.GH_TOKEN }}"'

    - name: Terraform Apply
      if: ${{ github.event.inputs.terraform_action == 'apply' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.7
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: './dev'
        tf_actions_comment: true
        args: '-auto-approve -var="github_token=${{ secrets.GH_TOKEN }}"'

    - name: Terraform Destroy
      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.7
        tf_actions_subcommand: 'destroy'
        tf_actions_working_dir: './dev'
        tf_actions_comment: true
        args: '-auto-approve -var="github_token=${{ secrets.GH_TOKEN }}"'
